package gsonfromjson

import com.voovoo.antlr.GsonGenerator

this.metaClass.mixin(cucumber.api.groovy.Hooks)
this.metaClass.mixin(cucumber.api.groovy.EN)


class Universe {

    def resourceLoader() {
        return Thread.currentThread().contextClassLoader
    }

    def loadFileAsStream(String file) {
        def withLoader = resourceLoader()
        def loadedFile = withLoader.getResourceAsStream file

        return loadedFile
    }

    def jsonStore
    def rootClass
}

World {
    new Universe()


}

Before() {

}

Given(~/^I have a "([^"]*)" json file$/) { String json ->


    def file = loadFileAsStream json

    if ((reader = file?.newReader())) {

        reader.eachLine { line ->
            println line
        }
    } else {
        throw new Exception("Failed")
    }

    setJsonStore(json)


}
And(~/^I want the root class to be called "([^"]*)"$/) { String rootClassName ->

    setRootClass rootClassName

}
Then(~/^I generate POJO classess using the tool$/) { ->

    def tool = new GsonGenerator()

    tool.generateClasses(getJsonStore(), getRootClass(), "unknown")

}

And(~/^The "([^"]*)" was generated by the tool$/) { String arg1 ->
    // Write code here that turns the phrase above into concrete actions
}