import cucumber.api.PendingException

this.metaClass.mixin(cucumber.api.groovy.Hooks)
this.metaClass.mixin(cucumber.api.groovy.EN)

Given(~/^I have a "([^"]*)" json file$/) { String arg1 ->
    // Write code here that turns the phrase above into concrete actions
    throw new PendingException()
}

Given(~/^I want the root class to be called "([^"]*)"$/) { String arg1 ->
    // Write code here that turns the phrase above into concrete actions
    throw new PendingException()
}

Then(~/^I generate POJO classess using the tool$/) { ->
    // Write code here that turns the phrase above into concrete actions
    throw new PendingException()
}

Then(~/^The "([^"]*)" was generated by the tool$/) { String arg1 ->
    // Write code here that turns the phrase above into concrete actions
    throw new PendingException()
}