Feature: A text file with class code can be generated from a json input.

  Scenario:
    Given I have a "car.json" json file
    And I want the root class to be called "Car"
    And I expect that this class will be in "euro.vehicles" package
    Then I generate POJO classess using the tool
    And The "Car" was generated by the tool
    And This class is in expected package
    And I store this class as a java source file in appropriate package
    Then The "Car.java" java source file was generated in "euro/vehicles" directory